### ISSUE TITLE
Missing files in zju-mocap dataset

### ISSUE THREAD

**Issue by AlfredMarcel** [zju3dv/instant-nvr#1]
Thanks for your open source!  When I run on 377 sample, I got this problem.

![QQ截图20230613225358](https://github.com/zju3dv/instant-nvr/assets/49266277/c4bb09d4-34ff-4ad1-8b6b-85c9d7daf95b)

I did not find the bigpose_uv.npy file in my zju-mocap dataset. In addition, I also noticed that the dierctory of the dataset in this code is also different from the previous projects using zjumocap. (For example, the previous subject folder was named "Coreview_377" instead of "my_377", "joints.npy"'s path in this code is "smpl_lbs/" rather than "lbs/" in my zjumocap dataset. ) The following is part of my zjumocap directory.

![QQ截图20230613230340](https://github.com/zju3dv/instant-nvr/assets/49266277/88e70483-d08c-41b4-9395-77e0d6681196)

I downloaded the zju mocap dataset in October 2022. Does this mean that the dataset has been updated to a new version during this period? Should I re-acquire zjumocap to solve this problem?

**Comment by gcgeng** [comment]
> I downloaded the zju mocap dataset in October 2022. Does this mean that the dataset has been updated to a new version during this period? Should I re-acquire zjumocap to solve this problem?

Yes, your understanding is correct. The ZJU-MoCap dataset has been updated, so it should be acquired again. Please follow the instructions [here](https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#set-up-datasets).

**Comment by wkailiu** [comment]
​I also can not find the **bigpose_uv.npy** file in Refined_ZJU-Mocap.

![image](https://github.com/zju3dv/instant-nvr/assets/44597208/a3b87581-ea99-476e-95eb-f9dd77bb3153)

**Comment by rohitrango** [comment]
@wkailiu did you resolve this issue? I downloaded the refined version a few days ago but the file is not present.
