### ISSUE TITLE
How Can I render avatar in static tpose 

### ISSUE THREAD

**Issue by wyiguanw** [zju3dv/instant-nvr#11]
Thanks for your amazing work! I would like to know if I can render avatar in tpose, is there a script for that?

and the bullet-type render is not working. it seems like a "render_utils" file is missing

```
  File "/home/zilongwang/Research/Diffusion_Human/instant-nvr/lib/datasets/h36m/tpose_novel_view_dataset.py", line 12, in <module>
    from lib.utils import render_utils
ImportError: cannot import name 'render_utils' from 'lib.utils' (unknown location)
```

hope you can take a look at this part

**Comment by gcgeng** [comment]
I have uploaded the `render_utils` file, could you check whether it works?

We currently do not have such a script to render avatars in tpose, and maybe we will find some time to write it later. Please also let me know if you want to contribute this script to this repo, thanks!

**Comment by wyiguanw** [comment]
hi, sorry for the late reply. I try the` render_utils` file. and I met this issue:
```
Traceback (most recent call last):
  File "/home/zilongwang/Research/Diffusion_Human/instant-nvr/run.py", line 303, in <module>
    run_other(args.type)
  File "/home/zilongwang/Research/Diffusion_Human/instant-nvr/run.py", line 293, in run_other
    output = renderer.render(batch)
  File "/home/zilongwang/Research/Diffusion_Human/instant-nvr/lib/networks/renderer/inb_renderer.py", line 223, in render
    ret = self.get_pixel_value(ray_o, ray_d, near, far, occ, batch)
  File "/home/zilongwang/Research/Diffusion_Human/instant-nvr/lib/networks/renderer/inb_renderer.py", line 67, in get_pixel_value
    ret = self.get_density_color(wpts, viewdir, z_vals, raw_decoder)
  File "/home/zilongwang/Research/Diffusion_Human/instant-nvr/lib/networks/renderer/inb_renderer.py", line 40, in get_density_color
    wpts = wpts.view(n_batch * n_pixel * n_sample, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```
After debugging, I found that there is some wrong with ray generation in 'tpose_novel_view_dataset', the rays do not intersect with bbox. could you take a look at this part?

**Comment by gcgeng** [comment]
Could you provide your running command? Thanks

**Comment by wyiguanw** [comment]
python run.py --type bullet --cfg_file configs/inb/inb_377.yaml exp_name inb_377 gpus "1,"

the only thing I changed is the --type

**Comment by bring-nirachornkul** [comment]
Hi, I also have the same problem.

I can train it successfully


```
(instant-nvr) blinkdrive@blinkdrive-System-Product-Name:~/Documents/UNT/Project/instant-nvr$ python train_net.py --cfg_file configs/inb/inb_377.yaml exp_name inb_377
Current working directory: /home/blinkdrive/Documents/UNT/Project/instant-nvr
args =  Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='vis', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='vis', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
<class 'argparse.Namespace'>
True
Finish initialize part networks
Finish initialize network...
Hey, there exists an experiment with same name before. Please make sure you are continuing.
Finish initialize trainer...
Finish initialize optimizer...
Finish initialize lr scheduler...
Finish initialize recorder...
Finish initialize evaluator...
load model: exps/inb/inb_377/trained_model/latest.pth
[*] Training experiment inb_377 started, log_interval: 100
Training finished. Time elapsed: 1700850078.744202 seconds
```


But I can't render avatar in static tpose, same as the owner of this post.

```
(instant-nvr) blinkdrive@blinkdrive-System-Product-Name:~/Documents/UNT/Project/instant-nvr$ python run.py --type bullet --cfg_file configs/inb/inb_377.yaml exp_name inb_377
\Current working directory: /home/blinkdrive/Documents/UNT/Project/instant-nvr
args =  Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='bullet', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='bullet', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
<class 'argparse.Namespace'>
True
Finish initialize part networks
load model: exps/inb/inb_377/trained_model/latest.pth
the results are saved at exps/inb/inb_377/2023-11-24_12:29:08.405173
  0%|                                                                               | 0/100 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/run.py", line 303, in <module>
    run_other(args.type)
  File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/run.py", line 293, in run_other
    output = renderer.render(batch)
  File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/lib/networks/renderer/inb_renderer.py", line 223, in render
    ret = self.get_pixel_value(ray_o, ray_d, near, far, occ, batch)
  File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/lib/networks/renderer/inb_renderer.py", line 67, in get_pixel_value
    ret = self.get_density_color(wpts, viewdir, z_vals, raw_decoder)
  File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/lib/networks/renderer/inb_renderer.py", line 40, in get_density_color
    wpts = wpts.view(n_batch * n_pixel * n_sample, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```


My PC spec :

OS : Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
CPU : AMD Ryzen 5900X
Ram : 64 GBs
GPU : RTX 3090

**Comment by mimi40fzy** [comment]
> Hi, I also have the same problem.
> 
> I can train it successfully
> 
> ```
> (instant-nvr) blinkdrive@blinkdrive-System-Product-Name:~/Documents/UNT/Project/instant-nvr$ python train_net.py --cfg_file configs/inb/inb_377.yaml exp_name inb_377
> Current working directory: /home/blinkdrive/Documents/UNT/Project/instant-nvr
> args =  Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='vis', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
> Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='vis', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
> <class 'argparse.Namespace'>
> True
> Finish initialize part networks
> Finish initialize network...
> Hey, there exists an experiment with same name before. Please make sure you are continuing.
> Finish initialize trainer...
> Finish initialize optimizer...
> Finish initialize lr scheduler...
> Finish initialize recorder...
> Finish initialize evaluator...
> load model: exps/inb/inb_377/trained_model/latest.pth
> [*] Training experiment inb_377 started, log_interval: 100
> Training finished. Time elapsed: 1700850078.744202 seconds
> ```
> 
> But I can't render avatar in static tpose, same as the owner of this post.
> 
> ```
> (instant-nvr) blinkdrive@blinkdrive-System-Product-Name:~/Documents/UNT/Project/instant-nvr$ python run.py --type bullet --cfg_file configs/inb/inb_377.yaml exp_name inb_377
> \Current working directory: /home/blinkdrive/Documents/UNT/Project/instant-nvr
> args =  Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='bullet', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
> Namespace(cfg_file='configs/inb/inb_377.yaml', test=False, type='bullet', det='', local_rank=0, launcher='none', opts=['exp_name', 'inb_377'])
> <class 'argparse.Namespace'>
> True
> Finish initialize part networks
> load model: exps/inb/inb_377/trained_model/latest.pth
> the results are saved at exps/inb/inb_377/2023-11-24_12:29:08.405173
>   0%|                                                                               | 0/100 [00:01<?, ?it/s]
> Traceback (most recent call last):
>   File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/run.py", line 303, in <module>
>     run_other(args.type)
>   File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/run.py", line 293, in run_other
>     output = renderer.render(batch)
>   File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/lib/networks/renderer/inb_renderer.py", line 223, in render
>     ret = self.get_pixel_value(ray_o, ray_d, near, far, occ, batch)
>   File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/lib/networks/renderer/inb_renderer.py", line 67, in get_pixel_value
>     ret = self.get_density_color(wpts, viewdir, z_vals, raw_decoder)
>   File "/home/blinkdrive/Documents/UNT/Project/instant-nvr/lib/networks/renderer/inb_renderer.py", line 40, in get_density_color
>     wpts = wpts.view(n_batch * n_pixel * n_sample, -1)
> RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
> ```
> 
> My PC spec :
> 
> OS : Ubuntu 22.04.3 LTS Release: 22.04 Codename: jammy CPU : AMD Ryzen 5900X Ram : 64 GBs GPU : RTX 3090
I'm having the same issue, has anyone fixed it? 😭

**Comment by mimi40fzy** [comment]
I'm having the same issue, has anyone fixed it?😭

**Comment by gcgeng** [comment]
This issue has been fixed with commit https://github.com/zju3dv/instant-nvr/commit/d3c65ec2b7ca0cd3bfd9e19e79c6a0469b21eec5. Now you can use the following command to render bullet view of some static pose:
```bash
 python run.py --type bullet --cfg_file configs/inb/inb_377.yaml exp_name inb_377 gpus 0,
```

Let me know if you have any other questions.

Thanks,
Chen
