### ISSUE TITLE
About codes

### ISSUE THREAD

**Issue by oranges01** [zju3dv/instant-nvr#12]
Hi，
When reviewing the code, I found a portion that I don't quite understand. In "inb_part_network_multiassign.py" line 113"tpose = init_bigpose + resd".Isn't 'init_bigpose' here the pose under the initial T-pose, I'm a bit confused.

**Comment by gcgeng** [comment]
Here `init_bigpose` means the canonical geometry warped using only rigid linear blend skinning transforms, and `resd` means the predicted non-rigid deformation. By summing them up, we can get the final predicted geometry under canonical pose.

I hope this explanation helps. Please let me know if you have further questions.

**Comment by oranges01** [comment]
Thank for your replay. But in "inb_part_network_multiassign.py", line101 "init_tpose = pose_points_to_tpose_points(pose_pts_part_extend, A_bw=A_bw, R_inv=R_inv)" and 102 "init_bigpose = tpose_points_to_pose_points(init_tpose, A_bw=big_A_bw)", I 'm not sure that which one is canonical gemoetry warped using only rigid liner skinning transforms. This is what I confused.

**Comment by oranges01** [comment]
Oh, I've just reviewed your responses to other questions, and I think I understand why now. This can tranform "T-pose" to "大" pose.
