### ISSUE TITLE
Misalignment Between the Dataset and the Code

### ISSUE THREAD

**Issue by jingfengguo-ai** [zju3dv/instant-nvr#13]
Hi, Thank you for your great work! Some questions confuse me.
There's a lot of misalignment between the dataset and the code (tpose_dataset.py), like there is no bigpose_uv.npy in the CoreView_377 dataset, but in your code：
tuv = np.load(os.path.join(self.data_root, 'bigpose_uv.npy'))

**Comment by gcgeng** [comment]
Please read https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#zju-mocap-dataset

**Comment by jingfengguo-ai** [comment]
> Please read https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#zju-mocap-dataset

Thanks for your quick reply! I solved my problem
