### ISSUE TITLE
Can't find MonoCap Dataset

### ISSUE THREAD

**Issue by Fly-Pluche** [zju3dv/instant-nvr#14]
I couldn't find the relevant download link in the link([VCAI: VCAI-ASSETS (mpg.de)](https://gvv-assets.mpi-inf.mpg.de/)) you provided for MonoCap Dataset. Could you please provide a more detailed link?

**Comment by gcgeng** [comment]
For assistance with this specific issue, I recommend reaching out directly to the provider of the original dataset.
