### ISSUE TITLE
About point sampling by bigpose_uv.npy

### ISSUE THREAD

**Issue by markkim1115** [zju3dv/instant-nvr#15]
Hi, thanks for the sharing code and dataset.

I am curious how uv map coordinate is set, as far as i know, uv coordinate is pre-defined mapping relationship between vertex and 2D plane coordinate.

In your code, i think the uv map file is shape of 3D volume, you sample 2D coordinate with 3D trilinear interpolation.

(1) I want to know how you created file from SMPL vertex.

(2) From below code,

```
def pts_sample_uv(pts, uv, bounds, mode='bilinear'):
    """sample uv coords for points
    pts: n_batch, n_points, 3
    bw: n_batch, d, h, w, 2
    bounds: n_batch, 2, 3
    """

    pts = pts.clone()
    # interpolate blend weights
    min_xyz = bounds[:, 0]
    max_xyz = bounds[:, 1]
    bounds = max_xyz[:, None] - min_xyz[:, None]
    grid_coords = (pts - min_xyz[:, None]) / bounds
    grid_coords = grid_coords * 2 - 1
    # convert xyz to zyx, since the blend weight is indexed by xyz
    grid_coords = grid_coords.flip(-1)

    # the blend weight is indexed by xyz
    uv = uv.permute(0, 4, 1, 2, 3)
    grid_coords = grid_coords[:, None, None]
    uv = F.grid_sample(uv,
                       grid_coords,
                       mode=mode,
                       padding_mode='border',
                       align_corners=True)
    uv = uv[:, :, 0, 0]

    return uv
```

Specifically, for this code,
```
# convert xyz to zyx, since the blend weight is indexed by xyz
grid_coords = grid_coords.flip(-1)
```
I still confused why we need to flip last dimension.
Is uv map volume is defined (Z,Y,X,2) ??
I am confused about if volume locations are created with coordinate of vertex, I think the Z's value would be smallest one.
However, the actual shape of the uv volume tensor shape is (72,68,18,2), indeed looks like third-dimension(18) would be Z-dimension coordinate.

May be my elementary misunderstanding, thanks!

**Comment by gcgeng** [comment]
(1) Please refer to https://github.com/zju3dv/instant-nvr/blob/master/tools/prepare_zjumocap.py on details to obtain such files.
(2) This is also related to how you preprocess the volume. For the details, please refer to https://github.com/zju3dv/instant-nvr/blob/a6f4d68fd03ad7c7f75057aaceb69713ce56b584/tools/prepare_zjumocap.py#L164
