### ISSUE TITLE
How to estimate SMPL parameters like in the datasets

### ISSUE THREAD

**Issue by haodongw101** [zju3dv/instant-nvr#18]
Hello,

I've been working with the datasets provided in this repository (`ZJU_Mocap` and `MonoCap`) and encountered an issue when integrating custom data. The root of the problem lies in the difference between the SMPL parameters estimated by us and those provided with your datasets.

Could you share the method or tools used to estimate your dataset's SMPL parameters?

**Comment by gcgeng** [comment]
Please refer to https://github.com/zju3dv/EasyMocap.

Thanks,
Chen
