### ISSUE TITLE
normal in the ZJU-mocap dataset

### ISSUE THREAD

**Issue by Jiatttliu** [zju3dv/instant-nvr#19]
There are only a few datasets published in the readme:
└── zju-mocap
├── my_377
├── my_386
├── my_387
├── my_392
├── my_393
└── my_394
313, 315, 390 is missing,mainly the lack of normal among them. how can I make it up

**Comment by gcgeng** [comment]
The experiments in the paper were conducted on the provided datasets. For testing on custom dataset, please refer to #6.

Thanks,
Chen
