### ISSUE TITLE
Question about bweights (pbw)

### ISSUE THREAD

**Issue by louhz** [zju3dv/instant-nvr#2]
Hi, i want to transfer the zju-mocap from opencv to opengl coordinates.
And follow A-nerf, I need to perform the transformation matrix on RH and TH.
However, I notive that in instant-nvr, we also use the blending weight, So i am curious that Do I need to perform the coordinates 
transformation on this weight ?
I guess the answer is no since it is in the smpl coodinates

**Comment by gcgeng** [comment]
Although I don't have hands-on experience in converting SMPL parameters from OpenCV to OpenGL format, I hypothesize that such a transformation might not be necessary. Theoretically, blend weights do not interact directly with coordinate transformations. It would be great if you can share your insights after your attempt. Thank you!

**Comment by louhz** [comment]
> Although I don't have hands-on experience in converting SMPL parameters from OpenCV to OpenGL format, I hypothesize that such a transformation might not be necessary. Theoretically, blend weights do not interact directly with coordinate transformations. It would be great if you can share your insights after your attempt. Thank you!

Thanks for your suggestion, I will test it in both case
