### ISSUE TITLE
Someing wrong when training on Monocap dataset

### ISSUE THREAD

**Issue by Mr-ind1fferent** [zju3dv/instant-nvr#21]
An error occurred when I used the link to email to download the monocap dataset and used it to run instant-nvr.

![image](https://github.com/zju3dv/instant-nvr/assets/74087260/5b4aa60d-ad5d-4ab8-acfa-217b4e7ff79c)

Is there something wrong with the data but the Dc.Sida Peng already told me the dataset is already preprocessed?

**Comment by gcgeng** [comment]
Please add more information. Could you check whether you have downloaded the dataset from the correct location described here: https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md?

**Comment by Mr-ind1fferent** [comment]
> Please add more information. Could you check whether you have downloaded the dataset from the correct location described here: https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md?

![image](https://github.com/zju3dv/instant-nvr/assets/74087260/414aa85c-fe1a-4535-98e3-905a701a4ebc)

This is the error report for the first dataset, and the other three are similar, and I've sent an email and got the correct download address which the author told me the dataset are already been preprocessed. But now i am wondering if the dataset is propressed for the missing datafolder mask_cihp.

**Comment by gcgeng** [comment]
Please keep in mind that the monocap dataset used in this work is has a different data format from other works. Even if you have requested the dataset otherwhere, please always send me an email to request the latest dataset for this work.
