### ISSUE TITLE
How to Generate Human Masks for Custom Datasets

### ISSUE THREAD

**Issue by haodongw101** [zju3dv/instant-nvr#23]
Hi,

Thank you for the instructions on using custom datasets (#6). However, the instructions do not include how to generate human masks like the 'mask' and 'schp' folders in the MonoCap and ZJU-Mocap-Refine datasets.

Could you provide a simple guide on how to create human masks for custom datasets?

**Comment by gcgeng** [comment]
Thanks for your interest in our work! We have recently uploaded a instruction for custom data (including the mask processing part), which can be found here: https://github.com/zju3dv/instant-nvr/blob/master/docs/preprocess.md. Please let us know if you have any questions on this!

Thanks,
Chen
