### ISSUE TITLE
camera parameter for custom dataset

### ISSUE THREAD

**Issue by xianrui-luo** [zju3dv/instant-nvr#25]
I am trying to use this [https://github.com/zju3dv/instant-nvr/blob/master/docs/preprocess.md](url) to process custom monocular video, however, from easymocap I did not get camera parameters. I wonder where can I get them? Thank you.

**Comment by gcgeng** [comment]
Hello, we assume that the camera is static in the input video. As there is only one input video and the camera is static, there is no need to estimate the camera parameter.

**Comment by xianrui-luo** [comment]
In training I encounter this 
![image](https://github.com/user-attachments/assets/65937aa7-b9e8-48da-8429-9400068df7a2)
Maybe it is from incorrect camera parameters?  I use `emc --data config/datasets/svimage.yml --exp config/1v1p/hrnet_pare_finetune.yml --root ${data} --ranges 0 500 1 --subs 23EfsN7vEOA+003170+003670` but there is no intri and extri as output.

**Comment by gcgeng** [comment]
I think there might be some issues with the easymocap end. Could you coordinate with them to see where the issue comes from?

**Comment by xianrui-luo** [comment]
I use the transform in [https://github.com/skhu101/GauHuman/issues/26](url) to adjust the camera parameters, and now it is ok. Thank you for replying.
