### ISSUE TITLE
Unable to find bigpose_uv.npy file in the ZJU-Mocap dataset 

### ISSUE THREAD

**Issue by ctalegaonkar** [zju3dv/instant-nvr#5]
Hi, 
Thanks for the amazing work! I am trying to run the code base on ZJU-MoCap dataset, but in the dataset I downloaded, there are no 'bigpose_uv.npy' and "head_uv.obj" files. Did you create them separately? Or there's something wrong with the dataset I donwloaded?

**Comment by gcgeng** [comment]
Same as #1. Please refer to https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#zju-mocap-dataset for instructions on obtaining the refined ZJU-MoCap dataset.
