### ISSUE TITLE
Plan about instruction on running on custom datasets

### ISSUE THREAD

**Issue by Talegqz** [zju3dv/instant-nvr#6]
Thank you for your exceptional work. I greatly appreciate your efforts.

I would like to compare your method using custom datasets, but there are several things that I am unsure of how to obtain. 

Could you kindly provide a brief instruction on how to handle custom datasets? I would be grateful for your assistance.

**Comment by gcgeng** [comment]
Hi, thank you for your suggestion. We do have plans to write instructions for custom datasets. However, due to our current workload, we anticipate completing the instructions by the end of this month. Please stay tuned for updates!

**Comment by Talegqz** [comment]
@MrMorning Thanks for your reply. Waiting for your instructions.

**Comment by gcgeng** [comment]
We've provided a script to generate the auxiliary files needed for running our method in #7 
For custom datasets, please first use pose estimation frameworks like https://github.com/zju3dv/EasyMocap to generate the SMPL poses.
