### ISSUE TITLE
questions about zju-mocap

### ISSUE THREAD

**Issue by AlfredMarcel** [zju3dv/instant-nvr#9]
Thank you for your wonderful open source work! 
I would like to ask some questions about zju-mocap. Why were the original 313,315 and 390 subjects dropped? 390 subject wears loose clothes with a lot of folds, which I think is of significance for evaluation. I would like to ask why 313,315,390 subjects were not tested in instant-nvr paper. Will these subjects be used in zju-mocap later?

**Comment by gcgeng** [comment]
1. We follow the setting of human-nerf for convenient comparison - they did not test the sequences that you mentioned. 
2. Another reason is that we assume monocular inputs in our experiments, and those sequences do not provide enough information from a monocular view to perform the full-body reconstruction.

I hope this answers your issue. Please feel free to reopen the issue if you have further questions.

Best,
Chen

**Comment by AlfredMarcel** [comment]
Thank you for your answer. Humannerf has done experiments on these three subjects, and the results are quite good, in its supplementary materials. So I think it's still possible to reconstruct the whole body from monocular video.
![image](https://github.com/zju3dv/instant-nvr/assets/49266277/d586ddc5-dfad-41cc-8332-1058330b3909)

**Comment by gcgeng** [comment]
Thank you for providing the additional information in the supplementary
materials of human-nerf.

Actually, the setting in human-nerf's main text has become somewhat a
standard practice in many following-up works of it, e.g., MonoHuman[1]. It
might be possible to do the reconstruction, yet we have not tried it on
these additional sequences.

[1] MonoHuman: Animatable Human Neural Field from Monocular Video

Best,
Chen

**Comment by AlfredMarcel** [comment]
Thank you for your response. Now I comprehend.
